# Generated by Django 6.0.2 on 2026-02-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='', max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail')),
                ('subject', models.CharField(max_length=200, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Admin Notes')),
                ('status', models.CharField(choices=[('new', 'Neu'), ('read', 'Gelesen'), ('replied', 'Beantwortet'), ('closed', 'Geschlossen')], default='new', max_length=20, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Kontakt-Nachricht',
                'verbose_name_plural': 'Kontakt-Nachrichten',
                'ordering': ['-created_at'],
            },
        ),
    ]
