# Generated by Django 6.0.2 on 2026-04-16 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='exdate',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='rrule',
            field=models.TextField(blank=True, null=True),
        ),
    ]
