# Generated by Django 6.0.2 on 2026-04-17 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0002_calendarevent_exdate_calendarevent_rrule'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='calendarevent',
            name='unique_uid_recurrence',
        ),
        migrations.AddConstraint(
            model_name='calendarevent',
            constraint=models.UniqueConstraint(fields=('uid', 'recurrence_id'), name='unique_uid_recurrence', nulls_distinct=False),
        ),
    ]
